language: python
sudo: false
python:
- '2.7'
deploy:
  provider: pypi
  user: Alex.F
  password:
    secure: woRForE5Jx8oxI04fhTRWxXFeDsW395Z3GP8dY1i7yIboK7esR1ND6ibKKsgsyZPUkuROLYz4/tgzP3e7KmQT2ys1k0Hj9wizVgBNqBl5gSvp5D3+4R6n0lOy4bx1uP4g2/JZIDVZXzUicoWh+P7+hGNF/8z9LsCcJAYeXqMcrdUj6WZyTFFyFlUE+1S7P8GF402PxhCq/POhbQAhTC3HDZ6b3RfT2UGd1mIJId/UEhSFtYxnjgQ96fI0QYqJIrd7ru+81rHBpxU1lsN4HJwj+gymfV3A2OI15Z7lwac/AbaUGvt6KB1HKDWYsM3CX8ZrHmgekfzb7vntuoV5me0B79W7WaznOxmXWWRe8OXaX87Lv/TiP0tyO1mgPC+9GAySDL9yV/HWUPBxLjuXHysUMlFgF5sMpTXnyibWTSifZ/G6rXZdQr69GPvJerC4QDRPK4tfMe+oH5REp5+/t4HlGPTpg6vhG0dbNuQLjBpGj7sN2n3PYutFfkdJAbbkk8r3pT91QG9ESscZJ0gHOpEPejKcsvuw5FOw75Sc5TI3PgZyWIqynVICqJN7WQl7Qf4MtG562hdHkU3w4K4+RVYP/EGNSUHeN421NTQykADg0qxGIzi4vZRLKMK0WIelBnt7Di9ltxVt5Z4WbELWGWFVH0D0zKI6LUCQZfxovEViT0=
  on:
    repo: gfreezy/Flask-Statsd
